### ISSUE TITLE
Replace automake with a cmake solution

### ISSUE THREAD

**Issue by sniperrifle2004** [sniperrifle2004/vba-rr#3]
Automake is a good enough solution, but it requires all kinds of artifacts that simply make no sense. cmake is much cleaner and should also make cross platform building simpler (since the actual build system is hidden under cmake)

**Comment by ProjectRevoTPP** [comment]
Would this allow OSX building?

**Comment by wilfriedvanasten** [comment]
It is possible, but I have no experience with mac development. At least there is a distribution for the platform, but depending on the exact build details, that might not be enough. It should make adding support for the platform much easier though

**Comment by sniperrifle2004** [comment]
Now tracked here: https://github.com/sniperrifle2004/vba-rerecording/issues/99
